### ISSUE TITLE
Alternative to KendoReact?

### ISSUE THREAD

**Issue by jinman** [philnash/twilio-chat-kendo-react#1]
Are there any other React UI components available that is free/MIT license that can work with Twilio Chat service and this repo? It looks like KendoReact is very expensive. Any recommendations?

**Comment by philnash** [comment]
I haven't looked into any others myself just yet, so I can't recommend any. However, a quick search on Google does bring up a few alternatives. Right now, I can only say that you should test them out yourself.

Thankfully, much of the work in this repo goes towards setting up Twilio Chat within React, so you should ultimately be able to swap out the mapping between message and user data formats and the UI framework to see the new one working.

I'd be interested to hear how you go with this.
