### ISSUE TITLE
proxy issue

### ISSUE THREAD

**Issue by AmanSonii** [philnash/twilio-chat-kendo-react#2]
Proxy error: Could not proxy request /video/token from localhost:3000 to http://localhost:3001/ (ECONNREFUSED)
I got the error mentioned above when I submit the form in order to join the room

**Comment by philnash** [comment]
This is a repo for a Twilio Programmable Chat example application. If you are making requests to `/video/token` are you changing this app somewhat or working with another repo?

Are you seeing anything in the log in your terminal?

**Comment by philnash** [comment]
Hi @AmanSonii,

I haven't heard back from you on this so I assume you have fixed your problem. I'm going to close this issue but feel free to comment if you still need help.
