### ISSUE TITLE
Module not found: Can't resolve 'babel-runtime/core-js/array/from' in when Testing this out with Next.js

### ISSUE THREAD

**Issue by jermsam** [philnash/twilio-chat-kendo-react#3]
I tried changing the twilio-chat version to the one in this example in vain. Thought the issue was with my 3.3.7 version but I was wrong

**Comment by jermsam** [comment]
I suggest you include in the docs that inclusion of ```babel-runtime``` dependency is a requirement.

**Comment by philnash** [comment]
Hey, sorry, not sure what you're asking here.

This project runs with the dependencies that it has defined. It sounds like you're trying to do something in another project and you are having a dependency problem? Can you elaborate a bit more?

**Comment by philnash** [comment]
Hi @jermsam, can you fill me in with some more details here? I'm not sure what I can do in this project to solve the problem at the moment.

**Comment by jermsam** [comment]
The problem gets resolved when the ```babel-runtime``` dependency is installed. My suggestion is that you include in the docs that it is required.

**Comment by philnash** [comment]
Hi @jermsam,

That's the thing, I don't have that problem when I run this project. So it's not a dependency to this project.

You mentioned you're using it in a Next.js project? Can you tell me what you did? I can't add anything to the docs that I don't really understand.

Thank you!
